version: "3"
services:
  dev-machine:
    build: .
    container_name: development-machine
    working_dir: /development
    restart: always
    volumes:
      - ./:/development
    tty: true
    ports:
      - 3000:3000
      - 4000:4000
      - 9000:9000
      - 19000:19000 # Specify port-forwarding
      - 19001:19001
      - 19002:19002
      - 19006:19006
      - 19007:19007
      - 19009:19009
